app/views/AltitudeView.js, views/AltitudeView.html
=> Added km/h functionality

app/Menu.js, app/util/SettingsLoader.js, app/util/Validator.js, app/views/AppSettingsView.js, app/views/ParentSettingsView.js, app/windows/app-settings.js, package.json, styles/main.css, styles/views/app-settings-view.css, styles/views/settings-view.css, views/AppSettingsView.html, windows/appSettings.html
=> App Settings Window

app/Menu.js, app/Network.js, app/views/NetworkSettingsView.js, app/windows/network-settings.js, config/network-config.js, styles/views/settings-view.css, views/NetworkSettingsView.html, windows/networkSettings.html
=> Network settings window

app/Menu.js, app/windows/console.js, windows/console.html
Just a seperate console window to make developing the application easier
=> Seperate console window

app/util/Logger.js
Was due to there being invalid characters in the date (no colons allowed)
=> Fixed logger error

app/App.js, app/models/Commands.js, app/views/AltitudeView.js, app/views/AttitudeView.js, app/views/EmergencyButtonsView.js, app/views/MainLayoutView.js, index.html, styles/views/altitude-view.css, styles/views/attitude-view.css, styles/views/cockpit-layout-view.css, styles/views/emergency-buttons-view.css, styles/views/main-layout-view.css, views/EmergencyButtonsView.html, views/MainLayoutView.html
=> Emergency buttons

app/views/EmergencyButtonsView.js
=> Added a confirmation before arming the plane

app/SimulationManager.js, app/StatusManager.js, app/connections/DataRelay.js, app/models/StatusMap.js, app/views/StatusView.js, styles/views/status-view.css
Basically more sophisticated statuses that can turn each other on and off.
=> Status Manager Constants Map

app/views/StatusView.js, styles/views/status-view.css, views/StatusView.html
=> Added transmission rate display on status manager

app/AircraftStatus.js, app/Menu.js, app/connections/DataRelay.js, app/map/PathManager.js, app/models/Commands.js, app/models/StatusMap.js, app/views/DataView.js, app/views/GainsAdjustView.js, app/views/MapView.js, app/windows/data-view.js, views/DataView.html, views/MapView.html, windows/dataView.html
Data window that displays the current autonomous data, making viewing the current status of the telemetry data easier.
=> Data window

app/views/StatusView.js, views/StatusView.html
=> Added RSSI display on status view

app/connections/DataRelay.js, app/models/TelemetryData.js, app/util/PacketParser.js, test/app/util/PacketParserTest.js
Essentially this module provides a centralized location for us to parse and validate the data received from the data relay station. Both SimulationManager and DataRelay modules will use the module.
This is also the first ever PR to include unit tests!
=> Packet Parser module

app/models/TelemetryData.js, test/app/models/TelemetryData.js
I removed the properties of the Telemetry Data module that werent actually used anywhere, as well as added helper functions to it for emitting and parsing data. Includes unit tests for the helper functions
=> Simplified Telemetry Data module and added helper functions

app/connections/DataRelay.js, app/models/Commands.js, test/app/connections/DataRelayTest.js
The DataRelay module has been refactored slightly to use the new TelemetryData module api. The Commands module has been updated to use the new SimulationManager API. At this point the app runs and is able to connect to the data relay and receive and send out data through its event emitters.
=> More Data Relay Fixes

app/Map.js, app/core/Menu.js, app/windows/map-view.js, package.json, templates/windows/mapView.html
Fixed the issue of the waypoints not updating on the path manager, preventing a path to be sent to the picpilot.
Also added a module, that when installed, will overwrite the git pre-commit hook, forcing you to make sure all unit tests are passing before commiting anything.
=> Fixed Map View Path Updating

app/models/Commands.js, app/views/GainsAdjustView.js
Sending all gains will now result in a third of the commands being sent.
=> Added multi gain command support

app/core/Menu.js, app/views/DataView.js, templates/views/DataView.html
It gets annoying when the values in the data view change from something to null. Basically added a checkbox to save the last valid state of the data, making it easier to read.
=> Added ability to semi-freeze data view

app/models/PacketTypes.js
- Added connection headers
- Removed probe drop header
=> Added uhf and xbee rssi headers

app/models/PacketTypes.js
Added checksum stuff to groundstation, to reflect changes in data relay and attitude manager.
=> added network checksum to the groundstation

app/models/PacketTypes.js, app/views/MapView.js
Added network compat stuff for following path button to toggle, and uncommented the handler for it
=> added pathfollowing to groundstation
